development:
  adapter: postgresql
  encoding: utf8
  database: help_me_decide_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: utf8
  database: help_me_decide_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: help_me_decide_production
  pool: 5